sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kjadhavaws/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kjadhavaws/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "locust-docker"
  env: "LocustDocker-env"
  bucket_name: "locust-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SCREAT_KEY